#!/usr/bin/env python3
"""Convert levels.json -> src/levels.c (prefer levels that have solutions)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEVELS_JSON = ROOT.parent / "levels.json"
OUT = ROOT / "src" / "levels.c"

MAX_W = 20
MAX_H = 18
MAX_LEVELS = 80
MAX_MAP_BYTES = 12000
MAX_SOL_BYTES = 14000
# Prefer shorter answers so more levels fit
MAX_SOL_PER_LEVEL = 400

CHAR_MAP = {
    " ": 0,
    "-": 0,
    "#": 1,
    ".": 2,
    "$": 3,
    "*": 4,
    "@": 5,
    "+": 6,
}

DIR_MAP = {
    "U": 0,
    "D": 1,
    "L": 2,
    "R": 3,
    "u": 0,
    "d": 1,
    "l": 2,
    "r": 3,
}


def pack_level(puzzle: list[str]) -> tuple[int, int, bytes]:
    h = len(puzzle)
    w = max(len(r) for r in puzzle)
    cells = []
    for y in range(h):
        row = puzzle[y]
        for x in range(w):
            ch = row[x] if x < len(row) else " "
            cells.append(CHAR_MAP.get(ch, 0))
    out = bytearray()
    for i in range(0, len(cells), 2):
        hi = cells[i]
        lo = cells[i + 1] if i + 1 < len(cells) else 0
        out.append((hi << 4) | lo)
    return w, h, bytes(out)


def pack_solution(sol: str) -> bytes:
    if not sol:
        return b""
    out = bytearray()
    for ch in sol:
        if ch in DIR_MAP:
            out.append(DIR_MAP[ch])
    return bytes(out)


def c_array(name: str, data: bytes, static: bool = True) -> list[str]:
    lines = []
    prefix = "static " if static else ""
    lines.append(f"{prefix}const unsigned char {name}[{len(data)}] = {{")
    row = []
    for b in data:
        row.append(f"0x{b:02X}")
        if len(row) == 16:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row))
    lines.append("};")
    return lines


def main() -> None:
    data = json.loads(LEVELS_JSON.read_text(encoding="utf-8"))
    candidates = []

    for i, lv in enumerate(data):
        puzzle = lv["puzzle"]
        h = len(puzzle)
        w = max(len(r) for r in puzzle)
        if w > MAX_W or h > MAX_H:
            continue
        s = "\n".join(puzzle)
        boxes = s.count("$") + s.count("*")
        goals = s.count(".") + s.count("*") + s.count("+")
        players = s.count("@") + s.count("+")
        if players != 1 or boxes == 0 or boxes != goals:
            continue
        ww, hh, packed = pack_level(puzzle)
        sol = pack_solution(lv.get("solution") or "")
        if len(sol) > MAX_SOL_PER_LEVEL:
            sol = b""  # skip huge answers for ROM budget
        candidates.append(
            {
                "idx": i,
                "name": lv.get("name", f"L{i}"),
                "w": ww,
                "h": hh,
                "packed": packed,
                "sol": sol,
            }
        )

    # Prefer levels that have answers, then original order
    candidates.sort(key=lambda c: (0 if c["sol"] else 1, c["idx"]))

    selected = []
    map_total = 0
    sol_total = 0
    for c in candidates:
        if len(selected) >= MAX_LEVELS:
            break
        if map_total + len(c["packed"]) > MAX_MAP_BYTES:
            continue
        sol = c["sol"]
        if sol and sol_total + len(sol) > MAX_SOL_BYTES:
            sol = b""
        selected.append((c["name"], c["w"], c["h"], c["packed"], sol))
        map_total += len(c["packed"])
        sol_total += len(sol)

    lines = []
    lines.append("/* Auto-generated by tools/gen_levels.py — do not edit */")
    lines.append('#include "game.h"')
    lines.append("")
    lines.append(f"const unsigned char LEVEL_COUNT = {len(selected)};")
    lines.append("")

    for i, (name, w, h, packed, sol) in enumerate(selected):
        lines.append(f"/* {i}: {name} {w}x{h} sol={len(sol)} */")
        lines.extend(c_array(f"level_{i}_data", packed))
        lines.append("")
        if sol:
            lines.extend(c_array(f"sol_{i}_data", sol))
            lines.append("")

    lines.append("const unsigned char level_w[] = {")
    lines.append("    " + ", ".join(str(s[1]) for s in selected))
    lines.append("};")
    lines.append("const unsigned char level_h[] = {")
    lines.append("    " + ", ".join(str(s[2]) for s in selected))
    lines.append("};")
    lines.append("")
    lines.append("const unsigned char * const level_ptrs[] = {")
    for i in range(len(selected)):
        lines.append(f"    level_{i}_data,")
    lines.append("};")
    lines.append("")

    lines.append("const unsigned char sol_len_lo[] = {")
    lines.append("    " + ", ".join(str(len(s[4]) & 0xFF) for s in selected))
    lines.append("};")
    lines.append("const unsigned char sol_len_hi[] = {")
    lines.append("    " + ", ".join(str((len(s[4]) >> 8) & 0xFF) for s in selected))
    lines.append("};")
    lines.append("")
    lines.append("const unsigned char * const sol_ptrs[] = {")
    for i, s in enumerate(selected):
        if s[4]:
            lines.append(f"    sol_{i}_data,")
        else:
            lines.append("    0,")
    lines.append("};")
    lines.append("")

    with_sol = sum(1 for s in selected if s[4])
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"Wrote {OUT}: {len(selected)} levels, map={map_total}B, "
        f"sol={sol_total}B ({with_sol} with answers)"
    )


if __name__ == "__main__":
    main()
