#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Write default pure PH identity program to sokoban.ph."""
from __future__ import annotations

from pathlib import Path

from ph import NIL, value_to_source

HERE = Path(__file__).resolve().parent
OUT = HERE / "sokoban.ph"


def main() -> None:
    src = value_to_source(NIL)  # ()
    OUT.write_text(
        "; Parenthesis Hell — identity (cat of state Value)\n"
        "; Generated by generate.py\n"
        + src
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({src!r})")


if __name__ == "__main__":
    main()
