#!/usr/bin/env python3
"""levels.json -> src/levels_data.c for GBA Sokoban."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEVELS_JSON = ROOT.parent / "levels.json"
OUT = ROOT / "src" / "levels_data.c"

MAX_W, MAX_H = 20, 18
MAX_LEVELS = 60
MAX_MAP_BYTES = 20000
MAX_SOL_BYTES = 20000
MAX_SOL_PER = 500

CHAR_MAP = {" ": 0, "-": 0, "#": 1, ".": 2, "$": 3, "*": 4, "@": 5, "+": 6}
DIR_MAP = {"U": 0, "D": 1, "L": 2, "R": 3, "u": 0, "d": 1, "l": 2, "r": 3}


def pack_level(puzzle):
    h = len(puzzle)
    w = max(len(r) for r in puzzle)
    cells = []
    for y in range(h):
        row = puzzle[y]
        for x in range(w):
            ch = row[x] if x < len(row) else " "
            cells.append(CHAR_MAP.get(ch, 0))
    out = bytearray()
    for i in range(0, len(cells), 2):
        hi = cells[i]
        lo = cells[i + 1] if i + 1 < len(cells) else 0
        out.append((hi << 4) | lo)
    return w, h, bytes(out)


def pack_sol(s):
    if not s:
        return b""
    return bytes(DIR_MAP[c] for c in s if c in DIR_MAP)


def carr(name, data):
    lines = [f"static const unsigned char {name}[{len(data)}] = {{"]
    row = []
    for b in data:
        row.append(f"0x{b:02X}")
        if len(row) == 16:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row))
    lines.append("};")
    return lines


def main():
    data = json.loads(LEVELS_JSON.read_text(encoding="utf-8"))
    cands = []
    for i, lv in enumerate(data):
        p = lv["puzzle"]
        h, w = len(p), max(len(r) for r in p)
        if w > MAX_W or h > MAX_H:
            continue
        s = "\n".join(p)
        boxes = s.count("$") + s.count("*")
        goals = s.count(".") + s.count("*") + s.count("+")
        pl = s.count("@") + s.count("+")
        if pl != 1 or boxes == 0 or boxes != goals:
            continue
        ww, hh, packed = pack_level(p)
        sol = pack_sol(lv.get("solution") or "")
        if len(sol) > MAX_SOL_PER:
            sol = b""
        cands.append((lv.get("name", f"L{i}"), ww, hh, packed, sol, i))

    # Prefer with answers, then original order
    cands.sort(key=lambda c: (0 if c[4] else 1, c[5]))

    selected = []
    mt = st = 0
    for name, w, h, packed, sol, _ in cands:
        if len(selected) >= MAX_LEVELS:
            break
        if mt + len(packed) > MAX_MAP_BYTES:
            continue
        if sol and st + len(sol) > MAX_SOL_BYTES:
            sol = b""
        selected.append((name, w, h, packed, sol))
        mt += len(packed)
        st += len(sol)

    lines = [
        "/* Auto-generated by tools/gen_levels.py */",
        '#include "levels.h"',
        "",
        f"const unsigned char LEVEL_COUNT = {len(selected)};",
        "",
    ]
    for i, (name, w, h, packed, sol) in enumerate(selected):
        lines.append(f"/* {i}: {name} {w}x{h} sol={len(sol)} */")
        lines.extend(carr(f"level_{i}_data", packed))
        lines.append("")
        if sol:
            lines.extend(carr(f"sol_{i}_data", sol))
            lines.append("")

    lines.append("const unsigned char level_w[] = {")
    lines.append("    " + ", ".join(str(s[1]) for s in selected))
    lines.append("};")
    lines.append("const unsigned char level_h[] = {")
    lines.append("    " + ", ".join(str(s[2]) for s in selected))
    lines.append("};")
    lines.append("const unsigned char * const level_ptrs[] = {")
    for i in range(len(selected)):
        lines.append(f"    level_{i}_data,")
    lines.append("};")
    lines.append("const unsigned short sol_len[] = {")
    lines.append("    " + ", ".join(str(len(s[4])) for s in selected))
    lines.append("};")
    lines.append("const unsigned char * const sol_ptrs[] = {")
    for i, s in enumerate(selected):
        lines.append(f"    sol_{i}_data," if s[4] else "    0,")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    nsol = sum(1 for s in selected if s[4])
    print(f"Wrote {OUT}: {len(selected)} levels, map={mt}B sol={st}B ({nsol} answers)")


if __name__ == "__main__":
    main()
